### ISSUE TITLE
Error updating water usage data: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by pvdham** [parvez/acwd_water_usage#5]
I tried with latest HA (downloaded today) and it failed to integrate and work. The error message is as follows for this custom integraion , with a note to report the issue. (modied logs with PII information)

```
2025-01-05 10:43:25.738 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'acwd_water_usage' calls async_forward_entry_setup for integration, acwd_water_usage with title: ACWD Water Usage and entry_id: XXXX, which is deprecated, await async_forward_entry_setups instead at custom_components/acwd_water_usage/__init__.py, line 10: hass.async_create_task(. This will stop working in Home Assistant 2025.6, please report it to the author of the 'acwd_water_usage' custom integration
2025-01-05 10:43:26.362 ERROR (MainThread) [custom_components.acwd_water_usage.sensor] Error updating water usage data: 'str' object has no attribute 'get'
2025-01-05 10:43:26.370 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration acwd_water_usage with title: ACWD Water Usage and entry_id: XXXX, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1, please report this issue
```
